export enum ApiStatus {
    USER_NOT_FOUND = "USER_NOT_FOUND",
    TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
    SUBJECT_NOT_FOUND = "SUBJECT_NOT_FOUND",
    COURSE_NOT_FOUND = "COURSE_NOT_FOUND",
    USER_EXISTS = "USER_EXISTS",
}
