export enum ApiStatus {
    USER_NOT_FOUND = "USER_NOT_FOUND",
    TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
    SUBJECT_NOT_FOUND = "SUBJECT_NOT_FOUND",
    COURSE_NOT_FOUND = "COURSE_NOT_FOUND",
    USER_EXISTS = "USER_EXISTS",
    PPI_NOT_FOUND = "PPI_NOT_FOUND",
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
    PROJECT_IS_FINISHED = "PROJECT_IS_FINISHED",
    GROUP_NOT_FOUND = "GROUP_NOT_FOUND",
}
